---
- name: "PLAY 1: Configure All Lan Devices"
  hosts: lan
  tags: lan
  connection: network_cli
  tasks:
    - name: "P1T1: Configure Hostname and Domain Name"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"

    - name: "P1T2: Configure Managment Static Routes"
      ios_static_route:
        prefix: "{{ item.prefix.split('/')[0] }}"
        mask: "{{ item.prefix | ipv4('netmask') }}"
        next_hop: "{{ item.next_hop }}"
      loop: "{{ mgmt_static_routes }}"
      register: ios_static_routes

    - name: "P1T3: Configure Interfaces"
      ios_interface:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        duplex: "{{ intf_duplex }}"
        mtu: "{{ intf_mtu }}"
        state: up
      loop: "{{ interfaces[inventory_hostname] }}"
      register: ios_intf

    - name: "P1T4: Create L2 VLANs"
      ios_vlan:
        aggregate: "{{ vlans }}"
      register: ios_vlans
      tags: vlan

    - name: "P1T5: Configure L2 Trunks"
      ios_l2_interface:
        name: "{{ item.name }}"
        mode: "{{ item.mode }}"
        trunk_allowed_vlans: "{{ vlans | map(attribute='vlan_id') | join(',') }}"
        state: present
      loop: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','trunk') | list }}"

    - name: "P1T6: Enable dot1q Trunks"
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
        parents: interface {{item.name}}
      loop: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','trunk') | list }}"
      tags: dot1q

    - name: "P1T7: Configure Access Ports"
      ios_l2_interface:
        name: "{{ item.name }}"
        mode: "{{ item.mode}}"
        access_vlan: "{{ item.vlan }}"
        state: present
      loop: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','access') | list }}"

- name: "PLAY 2: Configure Core Switches"
  hosts: core
  tags: l3_core
  tasks:

    - name: "P1T1: Create L2 Core VLANs"
      ios_vlan:
        vlan_id : "{{item.vlan_id | int}}"
        interfaces: "{{ item.interface}}"
      loop: "{{ core_vlans }}"
      tags: vlan

    - name: "P1T2: Allow Core VLANs on Core Trunk"
      ios_l2_interface:
        name: "{{ item.interface }}"
        mode: trunk
        trunk_allowed_vlans: "{{ (vlans + core_vlans) | 
                                  map(attribute='vlan_id') | 
                                  join(',') }}"
        state: present
      loop: "{{ core_vlans }}"


    - name: "P2T1: Create L3 VLAN Interfaces"
      ios_l3_interface:
        name: "{{item.name }}"
        ipv4:  "{{item.ipv4 | ipv4(hst_svi_id)}}"
      loop: "{{svi_interfaces}}"
      tags: l3_svi

    - name: "P2T2: Enable the VLAN Interfaces"
      ios_interface:
        name: "{{ item.name }}"
        state: up
      loop: "{{ svi_interfaces }}"

    - name: "P2T3: Create VRRP Configs"
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - vrrp {{item.name.split('Vlan')[1]}} priority {{ hst_vrrp_priority }}
          - vrrp {{item.name.split('Vlan')[1]}} ip {{item.ipv4 | ipv4(254)|ipaddr('address')}}
      loop: "{{svi_interfaces | selectattr('vrrp','equalto',true) | list }}"

    - name: "P2T4: Create WAN Links"
      ios_interface:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        duplex: "{{ intf_duplex }}"
        mtu: "{{ intf_mtu }}"
        state: up
      when: "'Loopback0' not in item.name"
      loop: "{{ core_l3_links[inventory_hostname] }}"


    - name: "P2T5: Make Wan Interfaces as L3 Interfaces"
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - no switchport
        save_when: changed
      loop: "{{core_l3_links[inventory_hostname]}}"
      when: "'Loopback0' not in item.name"

    - name: "P2T6: Configure IP Address on WAN Links"
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 | ipv4(1) }}"
      loop: "{{ core_l3_links[inventory_hostname] }}"
      when: "'Loopback0' not in item.name"

    - name: "P2T6: Configure IP Address on Loopbacko"
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 | ipv4(hst_router_id) }}"
      loop: "{{ core_l3_links[inventory_hostname] }}"
      when: "'Loopback0'  in item.name"
      tags: lo0

    - name: "P2T8: Configure OSPF"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines:
          - router-id {{ loopback_prefix | ipv4(hst_router_id) | ipaddr('address')}}

    - name: "P2T9: Configure OSPF On Interfaces"
      ios_config:
        parents: interface {{ item.name }}
        lines: 
          - ip ospf {{ ospf_process }} area {{ ospf_area }}
          - ip ospf network point-to-point
          - ip ospf cost {{item.ospf_metric | default(ospf_metric)}}
      loop: "{{ (svi_interfaces + core_l3_links[inventory_hostname]) | selectattr('ospf') | list }}"

    - name: "P2T10: Configure OSPF Passive Interfaces"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines: passive-interface {{item.name}}
      loop: "{{ (svi_interfaces + core_l3_links[inventory_hostname]) | selectattr('ospf','equalto','passive') | list }}"



- name: "PLAY 3: Configure WAN Routers"
  hosts: wan
  tags: wan
  tasks:
    - name: "P3T1: Configure System parameters"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"

    - name: "P3T2: Configure Managment Static Routes"
      ios_static_route:
        prefix: "{{ item.prefix.split('/')[0] }}"
        mask: "{{ item.prefix | ipv4('netmask') }}"
        next_hop: "{{ item.next_hop }}"
      loop: "{{ mgmt_static_routes }}"
      register: ios_static_routes

    - name: "P3T3: Configure All Interfaces"
      ios_interface:
        name: "{{ item.name }}"
        description: "{{ item.description | default('') }}"
        mtu: "{{ intf_mtu }}"
        state: up
      loop: "{{ wan_l3_links[inventory_hostname] }}"
      register: ios_intf

    - name: "P3T4: Configure IP Addresses towards Core"
      ios_l3_interface:
        name: "{{item.name }}"
        ipv4:  "{{item.ipv4 | ipv4(2)}}"
      loop: "{{wan_l3_links[inventory_hostname]}}"
      when: "'core' in item.peer"

    - name: "P3T4: Configure Loopback IP address"
      ios_l3_interface:
        name: "{{item.name }}"
        ipv4:  "{{item.ipv4 }}"
      loop: "{{wan_l3_links[inventory_hostname]}}"
      when: "'Loopback0' in item.name"

    - name: "P3T4: Configure IP Addresses on Wan P2P"
      ios_l3_interface:
        name: "{{item.name }}"
        ipv4:  "{{item.ipv4 | ipv4(hst_p2p_id)}}"
      loop: "{{wan_l3_links[inventory_hostname]}}"
      when: "'wan' in item.peer"


    - name: "P3T6: Configure OSPF"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines:
          - router-id {{ loopback_prefix | ipv4(hst_p2p_id) | ipaddr('address')}}

    - name: "P3T7: Configure OSPF On Interfaces"
      ios_config:
        parents: interface {{ item.name }}
        lines: 
          - ip ospf {{ ospf_process }} area {{ ospf_area }}
          - ip ospf network point-to-point
          - ip ospf cost {{item.ospf_metric | default(ospf_metric)}}
      loop: "{{ wan_l3_links[inventory_hostname] selectattr('ospf') | list }}"

    - name: "P3T8: Configure OSPF Passive Interfaces"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines: passive-interface {{item.name}}
      loop: "{{ grp_l3_links[inventory_hostname] | selectattr('ospf','equalto','passive') | list }}"



