---
- name: "PLAY 1: Configure All LAN Interfaces"
  hosts: lan
  tags: lan
  connection: network_cli
  tasks:
    - name: "P1T1: Configure Hostname and Domain Name"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"

    - name: "P1T2: Configure Managment Static Routes"
      ios_static_route:
        prefix: "{{ item.prefix.split('/')[0] }}"
        mask: "{{ item.prefix | ipv4('netmask') }}"
        next_hop: "{{ item.next_hop }}"
      loop: "{{ mgmt_static_routes }}"
      register: ios_static_routes
    - debug: var=ios_static_routes

    - name: "P1T3: Configure Interfaces"
      ios_interface:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        duplex: "{{ intf_duplex }}"
        mtu: "{{ intf_mtu }}"
        state: up
      loop: "{{ interfaces[inventory_hostname] }}"
      register: ios_intf

    - name: "P1T4: Create L2 VLANs"
      ios_vlan:
        aggregate: "{{ vlans }}"
      register: ios_vlans
      tags: vlan


    - name: "P1T5: Configure L2 Trunks"
      ios_l2_interface:
        name: "{{ item.name }}"
        mode: trunk
        trunk_allowed_vlans: "{{ vlans | map(attribute='vlan_id') | join(',') }}"
        state: present
      loop: "{{ interfaces[inventory_hostname] }}"
      tags: add_vlan

    - name: "P1T6: Enable dot1q Trunks"
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
        parents: interface {{item.name}}
      loop: "{{ interfaces[inventory_hostname] }}"
      tags: dot1q

    - name: "P1T7: Create Core VLANs"
      ios_vlan:
        aggregate: "{{ grp_core_vlans }}"
      when: "'core' in group_names"

    - name: "P1T8: Configure L2 VLANs"
      ios_l2_interface:
        name: "{{ item.interface }}"
        mode: trunk
        trunk_allowed_vlans: "{{ (vlans + grp_core_vlans) | map(attribute='vlan_id') | join(',') }}"
        state: present
      loop: "{{ grp_core_vlans }}"
      when: "'core' in group_names"
      tags: add_vlan


- name: "PLAY 2: Configure Core L3 Interfaces"
  hosts: core
  tags: l3_core
  tasks:
    - name: "P2T1: Create L3 VLAN Interfaces"
      ios_l3_interface:
        name: "{{item.key }}"
        ipv4:  "{{item.value | ipv4(hst_ip_suffix)}}"
      with_dict: "{{grp_l3_interfaces}}"

    - name: "P2T2: Enable the VLAN Interfaces"
      ios_interface:
        name: "{{ item.key }}"
        state: up
      with_dict: "{{grp_l3_interfaces}}"

    - name: "P2T3: Create VRRP Configs"
      ios_config:
        parents: interface {{ item }}
        lines:
          - vrrp {{item.split('Vlan')[1]}} priority {{ hst_vrrp_priority }}
          - vrrp {{item.split('Vlan')[1]}} ip {{grp_l3_interfaces[item] | ipv4(254)|ipaddr('address')}}
      loop: "{{grp_vrrp_vlans}}"

    # - debug: msg={{grp_l3_interfaces[item] | ipv4(254)|ipaddr('address')}}
    #   tags: ip
    #   loop: "{{grp_vrrp_vlans}}"
    #   delegate_to: localhost
