---
- name: test
  hosts: ltm01
  connection: local
  tasks:
    # - bigip_device_facts:
    #     gather_subset: all
    #     provider:
    #         user: admin
    #         password: admin
    #         server: "{{ ansible_host }}"
    #         validate_certs: no

    - bigip_device_ntp:
        ntp_servers:
          - 172.20.1.33
        provider:
            user: admin
            password: admin
            server: "{{ ansible_host }}"
            validate_certs: no
        