---
- name: "Play 1: Generate Device Configuration"
  hosts: all
  connection: local
  tasks:
    - name: "P1T1: Build Configs Directory"
      file: path=configs  state=directory
      run_once: yes

    - name: "P1T1: Build Config Directory per Device"
      file: path=configs/{{ inventory_hostname }}  state=directory

    - name: "P1T1: Generate Managment Configuration"
      template:
        src: "{{ansible_network_os}}/mgmt.j2"
        dest: "configs/{{ inventory_hostname }}/mgmt.cfg"

    - name: "P1T1: Generate Interface Configuration"
      template:
        src: "{{ansible_network_os}}/intf.j2"
        dest: "configs/{{ inventory_hostname }}/intf.cfg"