vlans:
  - name: Data
    vlan_id: 10
  - name: Voice
    vlan_id: 20
  - name: Web
    vlan_id: 100
interfaces:
  core01:
    - name: Ethernet0/1
      description: access01_e0/1
    - name: Ethernet0/2
      description: access02_e0/1
    - name: Ethernet0/3
      description: core01_e0/3
    - name: Ethernet1/3
      description: core01_e1/3
    - name: Port-channel1
      description: access01_Po1
    - name: Port-channel2
      description: access01_Po2 
    - name: Port-channel10
      description: core02_Po10    
  core02:
    - name: Ethernet0/1
      description: access01_e0/2
    - name: Ethernet0/2
      description: access02_e0/2
    - name: Ethernet0/3
      description: core02_e0/3
    - name: Ethernet1/3
      description: core02_e1/3
    - name: Port-channel1
      description: access01_Po1
    - name: Port-channel2
      description: access01_Po2 
    - name: Port-channel10
      description: core01_Po10  
  access01:
    - name: Ethernet0/1
      description: core01_e0/1
    - name: Ethernet0/2
      description: core02_e0/1
    - name: Port-channel1
      description: core01_Po1
    - name: Port-channel2
      description: core02_Po2 
  access02:
    - name: Ethernet0/1
      description: core01_e0/2
    - name: Ethernet0/2
      description: core02_e0/2
    - name: Port-channel1
      description: core01_Po1
    - name: Port-channel2
      description: core02_Po2 

mgmt_static_routes:
  - prefix: 192.168.0.0/24
    next_hop: "{{ mgmt_net_gw }}"
  - prefix: 10.8.0.0/24
    next_hop: "{{ mgmt_net_gw }}"

l2_interfaces:
  core01:
    - interface: Port-channel1
      mode: trunk
    - interface: Port-channel2
      mode: trunk
    - interface: Port-channel10
      mode: trunk
  core02:
    - interface: Port-channel1
      mode: trunk
    - interface: Port-channel2
      mode: trunk
    - interface: Port-channel10
      mode: trunk
  access01:
    - interface: Port-channel1
      mode: trunk
    - interface: Port-channel2
      mode: trunk
  access02:
    - interface: Port-channel1
      mode: trunk
    - interface: Port-channel2
      mode: trunk

l2_port_channels:
  core01:
    - group: 1
      members: [Ethernet0/1]
    - group: 2
      members: [Ethernet0/2]
    - group: 10
      members: [Ethernet0/3, Ethernet1/3]
  core02:
    - group: 1
      members: [Ethernet0/1]
    - group: 2
      members: [Ethernet0/2]
    - group: 10
      members: [Ethernet0/3, Ethernet1/3]
  access01:
    - group: 1
      members: [Ethernet0/1]
    - group: 2
      members: [Ethernet0/2]
  access02:
    - group: 1
      members: [Ethernet0/1]
    - group: 2
      members: [Ethernet0/2]