wan_l3_links:
  wan01:
    - name: GigabitEthernet2
      description: "core01_e1/0"
      peer: core01
      ipv4: 10.3.1.0/30
      ospf: yes
      ospf_metric: 100
    - name: Loopback0
      ipv4: "{{ loopback_prefix | ipv4(hst_router_id)}}"
      ospf: passive
    - name: GigabitEthernet3
      description: "wan01_Gi3"
      peer: wan01
      ipv4: 10.3.1.8/30
  wan02:
    - name: GigabitEthernet2
      description: "core02_e1/0"
      peer: core02
      ipv4: 10.3.1.4/30
      ospf: yes
      ospf_metric: 200
    - name: Loopback0
      ospf: passive
    - name: GigabitEthernet3
      description: "wan01_Gi3"
      peer: wan01
      ipv4: 10.3.1.8/30