# BEGIN ANSIBLE MANAGED BLOCK
bgp_asn: 65102
bgp_peers:
    - peer: leaf01
      peer_ip: 172.31.1.11
      remote_as: 65001
    - peer: leaf02
      peer_ip: 172.31.1.13
      remote_as: 65002
    - peer: leaf03
      peer_ip: 172.31.1.15
      remote_as: 65003
    - peer: leaf03
      peer_ip: 172.31.1.17
      remote_as: 65003
    - peer: spine01
      peer_ip: 172.31.1.8
      remote_as: 65101
# END ANSIBLE MANAGED BLOCK
