---
- name: "Play 1: Execute Operational Commands"
  hosts: junos
  vars:
    log_folder: "logs"
    op_folder: "op_data"
    op_cmds:
      - show configuration
  tasks:
    - name: "P1T1: Build Directories to Store Data"
      block:
        - name: "Create folder to store Device config"
          file:
            path: "{{ log_folder }}"
            state: directory
      run_once: yes
      delegate_to: localhost

    - name: "P1T2: Get Running configs from Devices"
      junos_command:
        commands: "{{ op_cmds }}"
      register: show_run
    
    - name: "P1T3: Save Running Config per Device"
      copy:
        content: "{{ show_run.stdout[0] }}"
        dest: "{{ log_folder }}/{{ inventory_hostname }}.cfg"
    


