---
- name: Build GCP network
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - gcp_account_info.yml
  vars:
    ip_forwarding: yes
  tasks:
    # - set_fact:
    #     test: "{{ 'name' if (ip_forwarding is defined and ip_forwarding) else omit }}"
    # - debug: var=test
    - name: Build GCP Network
      import_role:
        name: gcp_net_build
      
    - name: Build VM Instances
      include_role:
        name: gcp_new_vm
      loop: "{{ compute_nodes }}"
      loop_control:
        loop_var: node


    # - name: Get Facts
    #   gcp_compute_network_facts:
    #     auth_kind: "{{ auth_kind }}"
    #     project: "{{ project }}"
    #     service_account_file: "{{ service_account_file }}"
    #   register: gcp_network
    # - debug: var=gcp_network 
