---
- name: "System Configuration"
  template:
    src: "{{ansible_network_os}}/mgmt.j2"
    dest: "{{config_dir}}/{{ inventory_hostname }}/00_mgmt.cfg"

- name: "Interface Configuration"
  template:
    src: "{{ansible_network_os}}/intf.j2"
    dest: "{{config_dir}}/{{ inventory_hostname }}/01_intf.cfg"

- name: "Underlay BGP Configuration"
  template:
    src: "{{ansible_network_os}}/underlay_bgp.j2"
    dest: "{{config_dir}}/{{ inventory_hostname }}/03_bgp.cfg"

- name: "Overlay BGP EVPN Configuration"
  template:
    src: "{{ansible_network_os}}/overlay_bgp.j2"
    dest: "{{config_dir}}/{{ inventory_hostname }}/04_evpn.cfg"

- name: "VLAN/VXLAN Configuration"
  template:
    src: "{{ansible_network_os}}/vxlan.j2"
    dest: "{{config_dir}}/{{ inventory_hostname }}/02_vxlan.cfg"
  when: inventory_hostname in access_interfaces.keys()
  tags: vxlan

# - name: "OSPF Configuration"
#   template:
#     src: "{{ansible_network_os}}/ospf.j2"
#     dest: "{{config_dir}}/{{ inventory_hostname }}/02_ospf.cfg"

# - name: "MPLS Configuration"
#   template:
#     src: "{{ansible_network_os}}/mpls.j2"
#     dest: "{{config_dir}}/{{ inventory_hostname }}/03_mpls.cfg"
